/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_machao_myndksecrecy_Secrety */

#ifndef _Included_com_example_machao_myndksecrecy_Secrety
#define _Included_com_example_machao_myndksecrecy_Secrety
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_machao_myndksecrecy_Secrety
 * Method:    getSecrety
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_machao_myndksecrecy_Secrety_getSecrety
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
